rootpath: null
sources:
  collaborators:
    source:
    - filename: program_info.yaml
      location: /programs/*/
  data:
    source:
    - filename: project_info.yaml
      location: /projects/*/
  funding:
    source:
    - filename: program_info.yaml
      location: /programs/*/
  locations:
    source:
    - filename: project_info.yaml
      location: /projects/*/
  members:
    source:
    - filename: member_info.yaml
      location: /people/
  outputs:
    source:
    - filename: project_info.yaml
      location: /projects/*/
  programs:
    source:
    - filename: program_info.yaml
      location: /programs/*/
  projects:
    source:
    - filename: project_info.yaml
      location: /projects/*/
