programs:
  - name: id
    type: UUID PRIMARY KEY
  - name: name
    type: TEXT
  - name: start_date
    type: DATE
  - name: end_date
    type: DATE
  - name: source_path
    type: TEXT

projects:
  - name: id
    type: UUID PRIMARY KEY
  - name: name
    type: TEXT
  - name: ethics
    type: INTEGER
  - name: start_date
    type: DATE
  - name: end_date
    type: DATE
  - name: data_path
    type: TEXT
  - name: program_id
    type: UUID
  - name: source_path
    type: TEXT

data:
  - name: id
    type: UUID PRIMARY KEY
  - name: category
    type: TEXT
  - name: modality
    type: TEXT
  - name: device
    type: TEXT

funding:
  - name: id
    type: UUID PRIMARY KEY
  - name: organization
    type: TEXT

members:
  - name: id
    type: UUID PRIMARY KEY
  - name: name
    type: TEXT
  - name: role
    type: TEXT
  - name: active
    type: BOOLEAN
  - name: valid
    type: BOOLEAN

locations:
  - name: id
    type: UUID PRIMARY KEY
  - name: name
    type: TEXT

outputs:
  - name: id
    type: UUID PRIMARY KEY
  - name: type
    type: TEXT

collaborators:
  - name: id
    type: UUID PRIMARY KEY
  - name: name
    type: TEXT
  - name: affiliation
    type: TEXT

program_members:
  - name: id
    type: UUID PRIMARY KEY
  - name: program_id
    type: UUID
  - name: member_id
    type: UUID

program_collaborators:
  - name: id
    type: UUID PRIMARY KEY
  - name: program_id
    type: UUID
  - name: collaborator_id
    type: UUID

program_funding:
  - name: id
    type: UUID PRIMARY KEY
  - name: program_id
    type: UUID
  - name: funding_id
    type: UUID
  - name: start_date
    type: DATE
  - name: end_date
    type: DATE
  - name: notes
    type: TEXT

project_members:
  - name: id
    type: UUID PRIMARY KEY
  - name: project_id
    type: UUID
  - name: member_id
    type: UUID

project_data:
  - name: id
    type: UUID PRIMARY KEY
  - name: project_id
    type: UUID
  - name: data_id
    type: UUID

project_outputs:
  - name: id
    type: UUID PRIMARY KEY
  - name: project_id
    type: UUID
  - name: output_id
    type: UUID
  - name: name
    type: TEXT
  - name: url
    type: TEXT
  - name: date
    type: DATE

project_locations:
  - name: id
    type: UUID PRIMARY KEY
  - name: project_id
    type: UUID
  - name: location_id
    type: UUID

project_participants:
  - name: id
    type: UUID PRIMARY KEY
  - name: project_id
    type: UUID
  - name: label
    type: TEXT
  - name: total
    type: INTEGER
  - name: collected
    type: INTEGER
  - name: attributes
    type: TEXT[]